### ISSUE TITLE
Rich list feature for Callisto explorer service

### ISSUE THREAD

**Issue by ghost** [EthereumCommonwealth/Proposals#21] opened 2018-07-14 13:17 UTC
## Proposal

**Add Rich list feature for Callisto Explorer https://cloexplorer.org**

Based on our open source callisto blockchain explorer service , I can create a list of addresses with features of sorting them with top balance of CLO.

With this it is possible to view the status of total supply and monitoring top balance accounts to see if someone dumps for the low price 😄 

It will take few days after I receive the bounty

## Source code

I've published the source code of Callisto Explorer with the support of Rich list 😄 

https://github.com/chainkorea/clo-explorer/commit/a71ccd977487547dd93dff93b53e91fe6dcc3b68

If anyone interested for this PR visit the page and leave your ideas here.

## Funding goal

+ Proposal is 40,000 CLO for one-time payment

+ CLO funding address is [0xCe62CdEd0aBCb96842644E4A5a4FB1f3693edE1C](https://cloexplorer.org/addr/0xce62cded0abcb96842644e4a5a4fb1f3693ede1c)

**Comment by charlesmaxl** [comment] 2018-07-15 03:10
There was a similar proposal [here](https://github.com/EthereumCommonwealth/Proposals/issues/12) that got accepted.

**Comment by akx20000a** [comment] 2018-07-15 07:37
@charlesmaxl Yes but it is different with token richlist feature, we can implement the feature with contract but it is for ERC20 token only, for mainnet we need different method

**Comment by yograterol** [comment] 2018-07-15 19:15
@akx20000a which is the deadline for this?

**Comment by akx20000a** [comment] 2018-07-15 19:43
@yograterol About the deadline of this proposal is none,

If I receive the bounty I will start integrating on cloexplorer.org asap and it will take about week to see it live

**Comment by yuriy77k** [comment] 2018-07-16 09:07
@akx20000a can you add [Token Rich List](https://github.com/EthereumCommonwealth/Proposals/issues/12) for Callisto Explorer too?

**Comment by akx20000a** [comment] 2018-07-16 12:04
@yuriy77k The parsing method we use doesn't support Token Rich list however I will try adopting it for cloexplorer.org at the future

**Comment by akx20000a** [comment] 2018-07-16 12:05
@yograterol @Dexaran I've only received bounty for https://github.com/EthereumCommonwealth/Proposals/issues/9 however didn't received for this proposal, may I ask for check??

**Comment by akx20000a** [comment] 2018-07-16 16:04
@yograterol Ok, thanks 👍

**Comment by hackmod** [comment] 2018-07-16 21:00
Token Rich list is related PR at ETC-explorer https://github.com/ethereumproject/explorer/pull/136
any suggestion are welcomed

**Comment by akx20000a** [comment] 2018-07-17 02:03
@hackmod Yes I've thought about that however that PR only supports Parity https://github.com/ethereumproject/explorer/pull/136/files#diff-fe45162970b441f082c6c624644a2ab5R70 and we need geth support + rich list . I think there is no rich list integration yet 😂

**Comment by akx20000a** [comment] 2018-07-17 03:35
@hackmod 와 이더제로 애들 가격만 개폭락하는줄 알았는데 익스플로어 잘 만들었네요~~

저희도 ethereumproject/explorer 에 이더제로 패치 조금 넣으면 안되나요??

**Comment by akx20000a** [comment] 2018-07-17 03:39
참고) https://github.com/ethereumproject/explorer/compare/master...etherzero-org:dev

**Comment by yograterol** [comment] 2018-07-17 04:23
@akx20000a English plz

**Comment by yuriy77k** [comment] 2018-07-17 10:06
Do you want get bounty before complete work?

**Comment by akx20000a** [comment] 2018-07-17 14:13
@yuriy77k Yes since it is a open source project and upgrade of existing service I would like to get a bounty before deploying it live, I will open the source of rich list generator right after when I receive the bounty

**Comment by yograterol** [comment] 2018-07-18 18:37
@akx20000a 

> Since Callisto has 645,996 blocks and millions of transactions it will take weeks to see them live

Can you use more server power to reach it?

**Comment by akx20000a** [comment] 2018-07-18 18:57
Source code published https://github.com/chainkorea/clo-explorer/commit/a71ccd977487547dd93dff93b53e91fe6dcc3b68

**Comment by Errol1886** [comment] 2018-07-23 17:16
When will the "Rich List" be viewable on [https://cloexplorer.org/richlist](https://cloexplorer.org/richlist)?

**Comment by akx20000a** [comment] 2018-07-23 18:12
@yuriy77k Our rich list generator is parsing all accounts on callisto network so it will take some time

```
ubuntu@ip-172-31-23-18:~$ sudo systemctl status explorer4
● explorer4.service - CLO Blockchain Explorer - Richlist
   Loaded: loaded (/etc/systemd/system/explorer4.service; disabled; vendor preset: enabled)
   Active: active (running) since Wed 2018-07-18 19:02:19 UTC; 4 days ago
 Main PID: 27476 (python3)
    Tasks: 18
   Memory: 768.1M
      CPU: 6d 3h 35min 11.800s
   CGroup: /system.slice/explorer4.service
           ├─27476 /usr/bin/python3 richlist_generator.py
           └─27488 /usr/local/bin/geth --callisto --exec        arr = [];       for (var i = 0; i <= 646227; i++) {         var block = eth.getBlock(i);         if (block != null) {           if (block.transactions != null && block.transactions.length != 0) {

Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.
```

Here is the log of our generator and I think it will take weeks to see them live

**Comment by hackmod** [comment] 2018-08-11 07:37
fully integrated with the original ETC-explorer is now available as a PR. https://github.com/ethereumproject/explorer/pull/165

**Comment by eosclassicteam** [comment] 2018-08-11 13:43
@hackmod tools/richlist.js is broken please check

```
ubuntu@ip-172-31-27-31:~/eosc-explorer/tools$ node richlist.js
config.json found.
Connecting localhost:8545...
* latestBlock = 388956
/home/ubuntu/eosc-explorer/node_modules/web3/lib/web3/method.js:72
        throw errors.InvalidNumberOfRPCParams();
        ^

Error: Invalid number of input parameters to RPC method
    at Object.InvalidNumberOfRPCParams (/home/ubuntu/eosc-explorer/node_modules/web3/lib/web3/errors.js:28:16)
    at Method.validateArgs (/home/ubuntu/eosc-explorer/node_modules/web3/lib/web3/method.js:72:22)
    at Method.toPayload (/home/ubuntu/eosc-explorer/node_modules/web3/lib/web3/method.js:115:10)
    at Object.send [as listAccounts] (/home/ubuntu/eosc-explorer/node_modules/web3/lib/web3/method.js:139:30)
    at async.waterfall.callback.error (/home/ubuntu/eosc-explorer/tools/richlist.js:26:19)
    at nextTask (/home/ubuntu/eosc-explorer/node_modules/async/dist/async.js:5310:14)
    at Object.waterfall (/home/ubuntu/eosc-explorer/node_modules/async/dist/async.js:5320:5)
    at makeParityRichList (/home/ubuntu/eosc-explorer/tools/richlist.js:24:9)
    at Object.<anonymous> (/home/ubuntu/eosc-explorer/tools/richlist.js:181:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
ubuntu@ip-172-31-27-31:~/eosc-explorer/tools$ nano richlist.js
ubuntu@ip-172-31-27-31:~/eosc-explorer/tools$ sudo netstat -tnlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:30303           0.0.0.0:*               LISTEN      27859/parity
tcp        0      0 127.0.0.1:8545          0.0.0.0:*               LISTEN      27859/parity
tcp        0      0 127.0.0.1:8546          0.0.0.0:*               LISTEN      27859/parity
```

**Comment by dataclub** [comment] 2018-08-29 10:00
Hey, there are some bugs in the rich list. 
1. Selecting "All" gives only 1 account
2. Selecting to "All" and back to "20" entries reset the list to first page!
3. i cant search my account ranking with the search field
4. i can´t scroll pages faster, so i must click everytime to next page to come to the last

**Comment by Errol1886** [comment] 2018-08-29 16:48
@dataclub 

Number 2 is not a bug. If I select "All" from the dropdown menu, and then select "20" from the dropdown menu, it shows me the top 20 accounts - which is what is meant to happen. Same as if I select "50" from the dropdown menu, I will be shown the top 50 accounts.

**Comment by dataclub** [comment] 2018-08-30 08:30
No its not right! Because if you go to step 3 and select "20" filtering, than you will go to first step again. But i think, that is right if you will show "20" entries from there where you are. so you can choose 50 from step 4 and you will become 50 entries from there now...

**Comment by akx20000a** [comment] 2018-08-31 00:10
cc @hackmod

**Comment by hackmod** [comment] 2018-08-31 04:57
Simply, "All" per page option has been removed and 200, 500 per page options added,
https://github.com/ethereumproject/explorer/pull/165/commits/e2e4d10a1042e0381c113f80cd537d9fbc157b15
I think the size of all accounts is too big to fit on one page at a time.

feel free to feedback to the original ETC-Explorer PR found at https://github.com/ethereumproject/explorer/pull/165

**Comment by akx20000a** [comment] 2018-08-31 08:50
They will feedback here since we use your version of rich list instead of mine,

And can you work for updating the library of MEW instead improving logo file? 😄 

https://github.com/kvhnuke/etherwallet/issues/1978

If you migrate them to v5 version we can get rid of this message when we connect trezor everytime

![mew2](https://user-images.githubusercontent.com/34651082/44902949-43b43680-ad46-11e8-8cfe-ae7ecbd2afba.png)

And this will disappear from CLO, ESN, PIRL, MUSIC, and most of the recently added coins

**Comment by akx20000a** [comment] 2018-09-01 15:11
@hackmod @dataclub Patch applied on cloexplorer.org,

please let me know if it is not solved

**Comment by Dexaran** [comment] 2019-01-28 07:39
@yograterol I think that we can close this proposal now.

@yuriy77k @hackmod any feedback?

**Closed** 2019-02-21 20:09 UTC
Labels: fully_paid, withdrawn

**Comment by hackmod** [comment] 2019-05-02 00:31
sorry for the inconvenience but

the original work of the richlist done by me. (https://github.com/ethereumclassic/explorer/pull/165)

but the bounty receiver was the airking.
(aka @akx20000a or @chainkoreauser or `@eosclassic` (not EOSclassic) or @BTenterprise recently)
he tried to make his own work but with no success. and copied my work and get the bounty finally.

as a result, a patch worker receives bounty, the original author does not receive any penny.

the richlist of the etc-explorer done by me, but I did not claim any bounty.
I am 20 years experienced open source developer in South Korea,
and I just wanted to contribute etc-explorer as an ethereum classic holder.

but I should say, the airking must be expelled out of the cryptocurrency world
as an opensource developer viewpoint, his behavior is nonsense.

and please review carefully recent PR at https://github.com/EthereumCommonwealth/etherwallet/pull/302

**Comment by ghost** [comment] 2019-05-02 04:09
You are lying @hackmod, you are @akx20000a or @eosclassic, why not hesitate about cheating and scamming people?

**Comment by hackmod** [comment] 2019-05-02 06:19
I am @wkpark 49 years old open-source developer https://gist.github.com/wkpark/a1f2ed516ba11e3cfd91d4e6041ecca4

not a high school teenager.
akx20000a (aka airking is an infamous scam developer in South Korea)
see also https://cointelegraph.com/news/bitcoin-platinum-created-by-south-korean-teenager-as-a-scam-local-market-erupts

**Comment by ghost** [comment] 2019-05-02 06:33
I am not @chainkoreauser or someone else. You must have some misunderstanding @hackmod. Hope the situation goes well for you two.

**Comment by ghost** [comment] 2019-05-02 07:44
So are you the teenager @hackmod? You are @akx20000a @eosclassic or https://cointelegraph.com/news/bitcoin-platinum-created-by-south-korean-teenager-as-a-scam-local-market-erupts . I've reported you for your recent scamming activity about Bitcoin Platinum thanks.

**Comment by hackmod** [comment] 2019-05-07 04:16
@akx20000a (aka airking) is the real scammer and he is the @chainkoreauser .  you don't have any proof but I have so many proofs about me.
I guess you don't have even little bit of proof yourself. cause chiankoreauser is only 2-years old account,
before you was born and github was born, this is my famous contribution to the glibc
http://migs.fr/FTP/01-Composants/Carte%20RAID/adaptec%206805/Adaptec%206805_CD/bootcd/usr/share/i18n/locales/ko_KR
